name: quikapp
description: "A new Flutter project."
publish_to: 'none'
version: ${VERSION_NAME}+${VERSION_CODE}

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  $( [ "${PUSH_NOTIFY}" = "true" ] && echo "  firebase_core: ^2.24.2" )
  $( [ "${PUSH_NOTIFY}" = "true" ] && echo "  firebase_messaging: ^14.7.9" )
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.2.0
  permission_handler: ^11.1.0
  $( [ "${IS_CAMERA}" = "true" ] && echo "  camera: ^0.10.5+9" )
  $( [ "${IS_LOCATION}" = "true" ] && echo "  geolocator: ^10.1.0" )
  $( [ "${IS_MIC}" = "true" ] && echo "  speech_to_text: ^6.5.1" )
  $( [ "${IS_CONTACT}" = "true" ] && echo "  contacts_service: ^0.6.3" )
  $( [ "${IS_BIOMETRIC}" = "true" ] && echo "  local_auth: ^2.1.8" )
  $( [ "${IS_CALENDAR}" = "true" ] && echo "  calendar_events: ^0.0.1" )
  $( [ "${IS_STORAGE}" = "true" ] && echo "  file_picker: ^6.1.1" )
  $( [ "${IS_CHATBOT}" = "true" ] && echo "  flutter_chat_ui: ^1.6.10" )
  $( [ "${IS_DEEPLINK}" = "true" ] && echo "  uni_links: ^0.5.1" )
  $( [ "${IS_SPLASH}" = "true" ] && echo "  flutter_native_splash: ^2.3.9" )
  $( [ "${IS_PULLDOWN}" = "true" ] && echo "  pull_to_refresh: ^2.0.0" )
  $( [ "${IS_BOTTOMMENU}" = "true" ] && echo "  flutter_svg: ^2.0.9" )
  $( [ "${IS_LOAD_IND}" = "true" ] && echo "  loading_animation_widget: ^1.2.0+4" )

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
