name: quikapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.2.0
  permission_handler: ^11.1.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  uni_links: ^0.5.1
  file_picker: ^6.1.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
