name: quikapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1 # This will be replaced by build script

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.2.0
  permission_handler: ^11.1.0
  camera: ^0.10.5+9
  geolocator: ^10.1.0
  speech_to_text: ^6.5.1
  contacts_service: ^0.6.3
  local_auth: ^2.1.8
  calendar_events: ^1.0.5
  file_picker: ^6.1.1
  flutter_chat_ui: ^1.6.10
  uni_links: ^0.5.1
  flutter_native_splash: ^2.3.9
  pull_to_refresh: ^2.0.0
  flutter_svg: ^2.0.9
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
