#!/bin/bash
# Default Email Configuration (can be overridden by API)
DEFAULT_SMTP_SERVER="smtp.gmail.com"
DEFAULT_SMTP_PORT="587"
DEFAULT_SMTP_USER="prasannasrie@gmail.com"
DEFAULT_SMTP_PASS="jbbf nzhm zoay lbwb"

# Default notification email addresses
NOTIFICATION_EMAIL_TO="prasannasrinivasan32@gmail.com"
NOTIFICATION_EMAIL_FROM="noreply@quikapp.co"

# QuikApp required variables for local/dev builds

export APP_NAME="Garbcode App"
export PKG_NAME="com.garbcode.garbcodeapp"
export BUNDLE_ID="com.garbcode.garbcodeapp"
export VERSION_NAME="1.0.22"
export VERSION_CODE="27"
export OUTPUT_DIR="output"
export ORG_NAME="Garbcode Apparels Private Limited"
export WEB_URL="https://garbcode.com/"
export EMAIL_ID="prasannasrinivasan32@gmail.com"
export IS_CHATBOT="true"
export IS_DEEPLINK="true"
export IS_SPLASH="true"
export IS_PULLDOWN="true"
export IS_BOTTOMMENU="false"
export IS_LOAD_IND="true"
export IS_CAMERA="false"
export IS_LOCATION="false"
export IS_MIC="true"
export IS_NOTIFICATION="true"
export IS_CONTACT="false"
export IS_BIOMETRIC="false"
export IS_CALENDAR="false"
export IS_STORAGE="true"
export LOGO_URL="https://raw.githubusercontent.com/prasanna91/QuikApp/main/logo-gc.png"
export SPLASH="https://raw.githubusercontent.com/prasanna91/QuikApp/main/logo-gc.png"
export SPLASH_BG=""
export SPLASH_BG_COLOR="#cbdbf5"
export SPLASH_TAGLINE="Welcome to Garbcode"
export SPLASH_TAGLINE_COLOR="#a30237"
export SPLASH_ANIMATION="zoom"
export SPLASH_DURATION="4"
export BOTTOMMENU_ITEMS='[{"label": "Home", "icon": "home", "url": "https://pixaware.co/"}, {"label": "services", "icon": "services", "url": "https://pixaware.co/solutions/"}, {"label": "About", "icon": "info", "url": "https://pixaware.co/who-we-are/"}, {"label": "Contact", "icon": "phone", "url": "https://pixaware.co/lets-talk/"}]'
export BOTTOMMENU_BG_COLOR="#FFFFFF"
export BOTTOMMENU_ICON_COLOR="#6d6e8c"
export BOTTOMMENU_TEXT_COLOR="#6d6e8c"
export BOTTOMMENU_FONT="DM Sans"
export BOTTOMMENU_FONT_SIZE="12"
export BOTTOMMENU_FONT_BOLD="false"
export BOTTOMMENU_FONT_ITALIC="false"
export BOTTOMMENU_ACTIVE_TAB_COLOR="#a30237"
export BOTTOMMENU_ICON_POSITION="above"
export BOTTOMMENU_VISIBLE_ON="home,settings,profile"
export firebase_config_android="https://raw.githubusercontent.com/prasanna91/QuikApp/main/google-services-gc.json"
export firebase_config_ios="https://raw.githubusercontent.com/prasanna91/QuikApp/main/GoogleService-Info-gc.plist"
export APPLE_TEAM_ID="9H2AD7NQ49"
export APNS_KEY_ID="V566SWNF69"
export APNS_AUTH_KEY_URL="https://raw.githubusercontent.com/prasanna91/QuikApp/main/AuthKey_V566SWNF69.p8"
export CERT_PASSWORD="User@54321"
export PROFILE_URL="https://raw.githubusercontent.com/prasanna91/QuikApp/main/Garbcode_App_Store.mobileprovision"
export CERT_CER_URL="https://raw.githubusercontent.com/prasanna91/QuikApp/main/apple_distribution.cer"
export CERT_KEY_URL="https://raw.githubusercontent.com/prasanna91/QuikApp/main/privatekey.key"
export APP_STORE_CONNECT_KEY_IDENTIFIER="F5229W2Q8S"
export CM_KEYSTORE_PASSWORD="opeN@1234"
export CM_KEY_ALIAS="my_key_alias"
export CM_KEY_PASSWORD="opeN@1234"
